![alt text](https://raw.githubusercontent.com/pytorch/pytorch/master/docs/source/_static/img/pytorch-logo-dark.png)

Pytorch is a deep learning framework with dynamic computational graph.

More in details it provides:

    - n-dimensional array with GPU support (ndarray) 
    - an automatic differentiation engine
    - a gradient based optimization packadge 
    - other utilities...
    
to begin install the library following the instruction found in http://pytorch.org/

In [1]:
import torch

pytorch support n-dimensional arrays with GPU support (torch.Tensor):

In [2]:
x = torch.Tensor(3, 3)
x

tensor([[ 1.2252e+16,  3.0750e-41,  8.4078e-45],
        [ 0.0000e+00,         nan,  2.5313e-12],
        [ 1.8617e+25,  4.0690e+31,  5.8855e-44]])

In [3]:
x.size()

torch.Size([3, 3])

A better way to initialize a random tensor is by using the torch.rand function that initialize the tensors with values in the 0-1 interval

In [4]:
x = torch.rand(3, 3)
x

tensor([[ 0.7318,  0.8388,  0.8325],
        [ 0.1349,  0.7580,  0.6671],
        [ 0.6772,  0.9205,  0.2149]])

In [5]:
y = torch.rand(3, 3)
y

tensor([[ 0.9496,  0.9533,  0.9117],
        [ 0.9713,  0.8830,  0.6493],
        [ 0.4699,  0.6172,  0.1780]])

we can now easily perform operations between tensors:

In [6]:
x + y

tensor([[ 1.6814,  1.7921,  1.7442],
        [ 1.1062,  1.6410,  1.3163],
        [ 1.1471,  1.5377,  0.3930]])

In [7]:
x @ y

tensor([[ 1.9009,  1.9522,  1.3601],
        [ 1.1778,  1.2096,  0.7339],
        [ 1.6382,  1.5911,  1.2534]])

In [8]:
x * y

tensor([[ 0.6949,  0.7996,  0.7590],
        [ 0.1310,  0.6693,  0.4331],
        [ 0.3182,  0.5681,  0.0383]])

or we can index some of the row and columns of the arrays:

In [9]:
y

tensor([[ 0.9496,  0.9533,  0.9117],
        [ 0.9713,  0.8830,  0.6493],
        [ 0.4699,  0.6172,  0.1780]])

In [10]:
y[1]

tensor([ 0.9713,  0.8830,  0.6493])

In [11]:
y[:, 1]

tensor([ 0.9533,  0.8830,  0.6172])

additionally view allows reshaping tensors (note it cretes a view so it not modifies the orginal tensor unless you specifically instruct to do so.

In [12]:
y.view(-1)

tensor([ 0.9496,  0.9533,  0.9117,  0.9713,  0.8830,  0.6493,  0.4699,
         0.6172,  0.1780])

In [13]:
y.view(-1, 1, 3)

tensor([[[ 0.9496,  0.9533,  0.9117]],

        [[ 0.9713,  0.8830,  0.6493]],

        [[ 0.4699,  0.6172,  0.1780]]])

In [14]:
y = y.view(-1, 1, 3)
y @ x

tensor([[[ 1.4410,  2.3584,  1.6224]],

        [[ 1.2696,  2.0818,  1.5372]],

        [[ 0.5477,  1.0259,  0.8412]]])

Pytorch provides numpy bindings 

In [15]:
ones = torch.ones(3,2)
ones

tensor([[ 1.,  1.],
        [ 1.,  1.],
        [ 1.,  1.]])

In [16]:
np_ones = ones.numpy()
np_ones

array([[1., 1.],
       [1., 1.],
       [1., 1.]], dtype=float32)

In [17]:
ones + 1

tensor([[ 2.,  2.],
        [ 2.,  2.],
        [ 2.,  2.]])

In [18]:
ones

tensor([[ 1.,  1.],
        [ 1.,  1.],
        [ 1.,  1.]])

In [19]:
ones.add_(1)

tensor([[ 2.,  2.],
        [ 2.,  2.],
        [ 2.,  2.]])

In [20]:
np_ones

array([[2., 2.],
       [2., 2.],
       [2., 2.]], dtype=float32)

you can additionally do the opposite

In [21]:
import numpy as np

In [22]:
np_zeros = np.zeros(3)
np_zeros

array([0., 0., 0.])

In [23]:
torch.from_numpy(np_zeros)

tensor([ 0.,  0.,  0.], dtype=torch.float64)

up to now we have seen ndarray support but that is it possbile even in already popular libraries such as numpy.

So what does pytorch have more than numpy?

## GPU Support

In [24]:
device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")

In [25]:
x = x.to(device)

In [26]:
y = y.view(3,3).to(device) # we are returning to the original y shape

In [27]:
x @ y

tensor([[ 1.9009,  1.9522,  1.3601],
        [ 1.1778,  1.2096,  0.7339],
        [ 1.6382,  1.5911,  1.2534]], device='cuda:0')

## Automatic differentiation 

In [28]:
from torch.autograd import Variable

In [29]:
x = torch.ones(2, 2, requires_grad=True)
x

tensor([[ 1.,  1.],
        [ 1.,  1.]])

In [30]:
y = x + 2

In [31]:
y

tensor([[ 3.,  3.],
        [ 3.,  3.]])

In [32]:
print(y.grad_fn)

In [33]:
z = y * y * 3
out = z.mean()
out

tensor(27.)

the function we defined is  the following 

$f(x) = \frac{1}{N+M}\sum^{N}_{i=1}\sum^{M}_{j=1}3*(x_{ij}+2)^2$

In [34]:
out

tensor(27.)

now we want to calculate the gradent of the function with respect to x and update x with respect of half of the gradient:

$x := x + \frac{1}{2} \nabla_x \ f(x)$

an exercise for you .. calculate the derivatives

In [35]:
out.backward()

In [36]:
x = x + x.grad / 2

In [37]:
x

tensor([[ 3.2500,  3.2500],
        [ 3.2500,  3.2500]])